### ISSUE TITLE
Are also slides of lecture sharable here?

### ISSUE THREAD

**Issue by euberdeveloper** [ila/TUM#45]
Ciao,

I don't know another way to ask this, is this repository just for personal notes or also for professors' slides and old exams?

**Comment by ila** [comment]
Exams are not allowed since it breaks copyright, as well as big portions of text/code written by professors or TAs (eg deep learning assignments). It is allowed to post things such as "list of topics that might come up in exams" as long as it is made by students. Portions from slides are allowed if they are cited and publicly available (eg, no documents protected with a password) but tbh I would not add whole batches of slides here, this repository is intended for class notes

**Comment by euberdeveloper** [comment]
Ok
